# This is a basic workflow to help you get started with Actions

name: CI-push-to-z-servers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: push-system-files
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UFC_OHIO_PEM }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa

          echo "Pushing System files"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa system_files/* ubuntu@${{ vars.Z1_IP }}:/home/ubuntu/UT2004Server/System/

      - name: push-ini-files
        shell: bash
        run: |
          # Load passwords into ini Files
          sed -i 's/AdminPassword={{PASSWORD}}/AdminPassword=${{ vars.ADMIN_PASSWORD }}/' inis/UT2004-TAM.ini

          echo "Pushing ini files"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  inis/* ubuntu@${{ vars.Z1_IP }}:/home/ubuntu/UT2004Server/System/
        
      - name: push-to-redirect
        shell: bash
        env:
          SSH_PASS=${{ secrets.REDIRECT_PASSWORD }}
        run: |
          apt-get install sshpass
          sshpass -e sftp -oBatchMode=no -b - ${{ secrets.REDIRECT_USERNAME }}@hosted26.nfoservers.com
          put system_files/*.uz2 public/

      - name: restart-z1
        if: github.event_name == 'workflow_dispatch'
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.Z1_IP }}
          pm2 restart 0

      - name: restart-z2
        if: github.event_name == 'workflow_dispatch'
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@{{ vars.Z2_IP }}
          pm2 restart 0
